name: CI (sql-faker)

on:
  push:
    branches: [main]
    paths:
      - 'packages/sql-faker/**'
      - '.github/workflows/sql-faker.yml'

defaults:
  run:
    working-directory: packages/sql-faker

jobs:
  test:
    name: Test (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3', '8.4', '8.5']
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring, pdo, pdo_mysql
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          working-directory: packages/sql-faker
      - run: composer test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring
          coverage: none
      - uses: ramsey/composer-install@v3
        with:
          working-directory: packages/sql-faker
      - run: composer lint
